### ISSUE TITLE
Testing an application that relies on a launch darkly client

### ISSUE THREAD

**Issue by thomas91310** [launchdarkly/go-client#137]
The `LDClient` has an offline mode which is nice but I want to be able to create my own feature flags in my tests and inject them into my own LD client inside my tests.
Is there currently a way to do this?
(I was looking at using the `FeatureStore` and `Upsert` custom flags I create in my tests into the `FeatureStore` then call my own function that relies on LaunchDarkly feature flag values)

Like this:
```golang
func Test_Test(t *testing.t) {
        // took makeTestFlag from a test in the codebase
	flag := makeTestFlag("mycooltestflag", 1, "yo", "hi")
	featureStore := ld.NewInMemoryFeatureStore(nil)
	featureStore.Upsert(ld.Features, flag)
        // took makeTestClient from a test in the codebase and I modified it to attach my own feature store
        ldClient := makeTestClient(featureStore)
        
        obj := NewObj()
        
       // myFunction makes multiple `StringVariation`
       // calls and updates properties inside `obj`
        obj.MyFunction(ldClient) 

        // the goal now is to assert on values contained in `obj`
}
```

I was hoping that an offline client will still look at what it has in memory but it doesn't seem to be the case (it always seems to be returning a nil objects/values).

Any suggestions without wrapping everything into an interface are welcome!

**Comment by eli-darkly** [comment]
You're correct that if you put the client into offline mode, it'll totally ignore the feature store. The simplest way to do something like this with out-of-the-box components is to use the `ldfiledata` package, as described [here](https://docs.launchdarkly.com/v2.0/docs/reading-flags-from-a-file).

In a unit test environment, this has the slight disadvantage of requiring you to put your test flag values in a file rather than constructing them entirely in code. However, it has the advantage that if you use the `flagValues` format, you don't need to deal with the details of the FeatureFlag data model at all, which is good because that model is subject to change (the FeatureFlag class really shouldn't be exported at all; it is visible for historical reasons related to how we use it in our internal Go code).

So, for instance, your code above could be adapted as follows. Say you have a file called `testdata/mycooltest.yml` that looks like this:

```
---
flagValues:
  mycooltestflag: yo
```

Then the test code would look like this:
```
func makeTestClient(dataFile string) {
        fileSource, _ := ldfiledata.NewFileDataSourceFactory(ldfiledata.FilePaths(dataFile))
        config := ldclient.DefaultConfig
        config.UpdateProcessor = fileSource
        config.SendEvents = false
        return ldclient.MakeCustomClient("fake-key", config, 5 * time.Second)
}

func Test_Test(t *testing.T) {
        ldClient := makeTestClient("./testdata/mycooltest.yml")
        obj := NewObj()
        
        // myFunction makes multiple `StringVariation`
        // calls and updates properties inside `obj`
        obj.MyFunction(ldClient) 
        // etc.
}
```
